### PR TITLE
available width works with :box

### PR DESCRIPTION
**Pull request by hans-d**

### CODE REVIEW

**Comment by hans-d** [comment]
Together with #18, and using `:box (:line-width -8 :color ,nano-dark-background)` this allows for a small gap between the modeline and the body of the text. Eg when using org mode with a lot of SRC blocks it is more distinct.

**Comment by hans-d** [comment]
in progress: https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html

**Comment by rougier** [comment]
I've rewrote the main function for rendering the headher line but I haven't pushed yet. I'll first commit my changes and then I will integrate your PR If it's still relevant.

**Comment by hans-d** [comment]
still relevant, updated code against latest master

**Comment by rougier** [comment]
Sorry, Im' late. Coudl you post a screenshot before / after?

**Comment by hans-d** [comment]
before:
Screenshot 2022-01-03 at 19 36 05

after:
image

Together with #18 and something like 
```elisp
  (defun my/nano-modeline--clearance-tweaks ()
    (seq-do (lambda(elt)
              (set-face-attribute elt nil
                        :box `(:line-width -8 :color ,nano-dark-background)))
            (seq-filter (lambda(elt)
                          (string-prefix-p "nano-modeline-" (symbol-name elt)))
                        (face-list))))
```
will make it clear the available width calculation is off

**Comment by hans-d** [comment]
combination of fixes and local customization:

image

**Comment by rougier** [comment]
Now I get it and I realized I never understood negative linewidth boxed before. Can you rebase your PR?

**Comment by hans-d** [comment]
rebased

**Comment by rougier** [comment]
Merged. I've pushed some small adjustments as well.

**Pull request merged**
