### PR TITLE
Fix funcall nano-modeline-user-mode

### LINKED ISSUE #16: does `nano-modeline-user-mode` work?
given `(funcall ,nano-modeline-user-mode)) `, I can't get `nano-modeline-user-mode` working. My elisp skills are not top notch, so I might be missing something how to properly set the variable to a custom function.
Perhaps an example would help?

### PR DESCRIPTION
**Pull request by hans-d**
Fixes #16

### CODE REVIEW

**Comment by hans-d** [comment]
in progress: https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html

**Comment by rougier** [comment]
Thanks. Di you gzt you copyright assignment ?

**Comment by hans-d** [comment]
Signed contract has been submitted (waiting for final confirmation by FSF), all current PR's have already been earmarked for the assignment

**Comment by hans-d** [comment]
assignment (past & future) completed

**Comment by rougier** [comment]
Thanks, I've merged. But then I wonder if we need to have two separate functions:

`nano-modeline-user-mode-p`:  To tell nano-modeline whether to use user-provided modeline.
`nano-modeline-user-mode`: The actual user mode-line

As it is currently, I think you cannot mix nano-modeline with user-modeline. Or did I miss something?

**Comment by hans-d** [comment]
`nano-modeline-user-mode-p` is not directly needed, but does fit better with the overal structure already present - and may be less compute intensive in cases where complex functionality is used.
The function should do some checking on what mode it is to return the correct mode-line, eg via a `cond` form.

**Pull request merged**
