### PR TITLE
Allow additional space to be customised

### PR DESCRIPTION
**Pull request by hans-d**

### CODE REVIEW

**Comment by hans-d** [comment]
in progress: https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html

**Comment by rougier** [comment]
Many thanks.  This will be merged after I commit latest changes (I'm late).

**Comment by hans-d** [comment]
rebased on master, and adjusted default values based on changes in master

**Comment by rougier** [comment]
Thanks and happy new year. What about the copyright assignment?

**Comment by hans-d** [comment]
Copyright assignment has been completed

**Pull request merged**
