### PR TITLE
spacer elements in modeline should also get a face

### PR DESCRIPTION
**Pull request by hans-d**

### CODE REVIEW

**Comment by elnawe** [comment]
Great fix, thanks!
image

**Comment by rougier** [comment]
Spacing elements are defined by the active/inactive face no? I failed to see the difference in the screenshot.

**Comment by rougier** [comment]
Can you rebase your PR?

**Comment by hans-d** [comment]
rebased / squashed

**Comment by rougier** [comment]
Thanks. Only one comment on right-margin-width.

**Comment by hans-d** [comment]
i've noticed that one is needed, as some trailing odd background is visible. (I have a right-margin-width > 0)

**Comment by rougier** [comment]
I was suggesting `right-margin-width` -> `(or right-margin-width 0)`

**Pull request closed without merging**
